spring:
  application:
    name: Guiodes-Authenticator
  datasource:
    url: jdbc:postgresql://localhost:5432/authenticator
    username: root
    password: root

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}