name: Docker Build, Tag, and Push

on:
  push:
    branches:
      - main

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Esperando aprovação manual
        uses: appleboy/telegram-action@0.0.6
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 'A pipeline precisa de sua aprovação. Aprove ou rejeite na seção "Actions" do GitHub.'
      - name: Esperando aprovação manual
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.GHUB_TOKEN }}
      - name: Aguardando aprovação
        run: |
          echo "Aguardando sua aprovação. Vá para 'Actions' no GitHub e aprove esta execução para continuar."
          echo "name=manual-approval::true" >> $GITHUB_ENV


  build-and-push:
    runs-on: ubuntu-latest
    needs: manual-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHUB_USERNAME }}
          password: ${{ secrets.GHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ghcr.io/guiodes/authenticator:latest

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/guiodes/authenticator:latest
