name: Docker Build, Tag, and Push

on:
  push:
    branches:
      - main

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Esperando aprovação manual
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 'A pipeline precisa de sua aprovação. Aprove ou rejeite na seção nesse link: https://github.com/GuiOdes/authenticator/issues'
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GHUB_TOKEN }}
          approvers: GuiOdes
          minimum-approvals: 1
          issue-title: "Requisição de aprovação de deploy"
          issue-body: "A pipeline precisa de sua aprovação. Aprove ou rejeite digitando /lgtm ou /approve ou /reject na seção 'Actions' do GitHub."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  build-and-push:
    runs-on: ubuntu-latest
    needs: manual-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHUB_USERNAME }}
          password: ${{ secrets.GHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ghcr.io/guiodes/authenticator:latest

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/guiodes/authenticator:latest
