name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run detekt
        run: ./gradlew detekt

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: detekt

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test
